services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"  # Puerto AMQP
      - "15672:15672" # Puerto de la UI de gestión
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest