spring:
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://localhost:9090 # Cambia por la URL del microservicio cuando esté listo
          predicates:
            - Path=/api/users/**
            - Path=/api/products/**
      globalcors:
        corsConfigs:
          '[/**]':
            allowedOrigins:  # o pon tu dominio/fronend
              - "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders:
              - "*"
            allowCredentials: true
    rabbitmq:
      host: localhost
      port: 5672
      username: guest
      password: guest
services:
  user:
    host: localhost
    port: 9000
  product:
    host: localhost
    port: 50053
  order:
    host: localhost
    port: 50054