spring:
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://localhost:9090 # Cambia por la URL del microservicio cuando esté listo
          predicates:
            - Path=/api/users/**
    rabbitmq:
      host: localhost
      port: 5672
      username: guest
      password: guest