// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: libs/protobufs/users.proto

package user

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_libs_protobufs_users_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_libs_protobufs_users_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_libs_protobufs_users_proto_rawDescGZIP(), []int{0}
}

func (x *User) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetUsersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int32                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUsersRequest) Reset() {
	*x = GetUsersRequest{}
	mi := &file_libs_protobufs_users_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUsersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUsersRequest) ProtoMessage() {}

func (x *GetUsersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_libs_protobufs_users_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUsersRequest.ProtoReflect.Descriptor instead.
func (*GetUsersRequest) Descriptor() ([]byte, []int) {
	return file_libs_protobufs_users_proto_rawDescGZIP(), []int{1}
}

func (x *GetUsersRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*User                `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserResponse) Reset() {
	*x = GetUserResponse{}
	mi := &file_libs_protobufs_users_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserResponse) ProtoMessage() {}

func (x *GetUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_libs_protobufs_users_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserResponse.ProtoReflect.Descriptor instead.
func (*GetUserResponse) Descriptor() ([]byte, []int) {
	return file_libs_protobufs_users_proto_rawDescGZIP(), []int{2}
}

func (x *GetUserResponse) GetUsers() []*User {
	if x != nil {
		return x.Users
	}
	return nil
}

var File_libs_protobufs_users_proto protoreflect.FileDescriptor

const file_libs_protobufs_users_proto_rawDesc = "" +
	"\n" +
	"\x1alibs/protobufs/users.proto\x12\ausuario\"\x1f\n" +
	"\x04User\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"*\n" +
	"\x0fGetUsersRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x05R\x06userId\"6\n" +
	"\x0fGetUserResponse\x12#\n" +
	"\x05users\x18\x01 \x03(\v2\r.usuario.UserR\x05users2L\n" +
	"\vUserService\x12=\n" +
	"\aGetUser\x12\x18.usuario.GetUsersRequest\x1a\x18.usuario.GetUserResponseBBZ@github.com/santig05/Distributed-Systems-gRPC/libs/protobufs;userb\x06proto3"

var (
	file_libs_protobufs_users_proto_rawDescOnce sync.Once
	file_libs_protobufs_users_proto_rawDescData []byte
)

func file_libs_protobufs_users_proto_rawDescGZIP() []byte {
	file_libs_protobufs_users_proto_rawDescOnce.Do(func() {
		file_libs_protobufs_users_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_libs_protobufs_users_proto_rawDesc), len(file_libs_protobufs_users_proto_rawDesc)))
	})
	return file_libs_protobufs_users_proto_rawDescData
}

var file_libs_protobufs_users_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_libs_protobufs_users_proto_goTypes = []any{
	(*User)(nil),            // 0: usuario.User
	(*GetUsersRequest)(nil), // 1: usuario.GetUsersRequest
	(*GetUserResponse)(nil), // 2: usuario.GetUserResponse
}
var file_libs_protobufs_users_proto_depIdxs = []int32{
	0, // 0: usuario.GetUserResponse.users:type_name -> usuario.User
	1, // 1: usuario.UserService.GetUser:input_type -> usuario.GetUsersRequest
	2, // 2: usuario.UserService.GetUser:output_type -> usuario.GetUserResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_libs_protobufs_users_proto_init() }
func file_libs_protobufs_users_proto_init() {
	if File_libs_protobufs_users_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_libs_protobufs_users_proto_rawDesc), len(file_libs_protobufs_users_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_libs_protobufs_users_proto_goTypes,
		DependencyIndexes: file_libs_protobufs_users_proto_depIdxs,
		MessageInfos:      file_libs_protobufs_users_proto_msgTypes,
	}.Build()
	File_libs_protobufs_users_proto = out.File
	file_libs_protobufs_users_proto_goTypes = nil
	file_libs_protobufs_users_proto_depIdxs = nil
}
