// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user.proto

package user;

public interface GetUserResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:user.GetUserResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .user.User users = 1;</code>
   */
  java.util.List<user.User> 
      getUsersList();
  /**
   * <code>repeated .user.User users = 1;</code>
   */
  user.User getUsers(int index);
  /**
   * <code>repeated .user.User users = 1;</code>
   */
  int getUsersCount();
  /**
   * <code>repeated .user.User users = 1;</code>
   */
  java.util.List<? extends user.UserOrBuilder> 
      getUsersOrBuilderList();
  /**
   * <code>repeated .user.User users = 1;</code>
   */
  user.UserOrBuilder getUsersOrBuilder(
      int index);
}
