// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user.proto

package user;

public interface GetUsersRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:user.GetUsersRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 user_id = 1;</code>
   * @return The userId.
   */
  int getUserId();
}
